dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
liquidity_pairs_list_percentage: 25
dex_info_process_cicle_minutes: 720
percentage_amount_to_use: 80
top_percentage_amount_to_request: 95
coingecko_prices_url: "https://api.coingecko.com/api/v3/simple/price?ids=ethereum,tether,usd-coin&vs_currencies=usd"
gasoracle_url: "https://api.etherscan.io/api?module=gastracker&action=gasoracle&apikey=76EIAGPFFB8GNK9Z8IGEAN85DMZER3DMN4"
etherscan_weth_abi: "https://api.etherscan.io/api?module=contract&action=getabi&address=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&apikey=76EIAGPFFB8GNK9Z8IGEAN85DMZER3DMN4"
token_weth: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
token_tether: "0xdac17f958d2ee523a2206206994597c13d831ec7"
token_usdc: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
minimum_weth_target: 1001
gas_type: "fast"
base_fee_multiplier: 2.0
gas_limit_start_swap: 330000
coingecko_prices_refresh_seconds: 20
token_value_min_threshould: 1000.00
remove_min_threshould_pairs: False
profit_level1: 1000.00
profit_level2: 10000.00
profit_level3: 50000.00
profit_level4: 100000.00
profit_level1_priority_feed_multiplier: 1.00
profit_level2_priority_feed_multiplier: 2.50
profit_level3_priority_feed_multiplier: 3.00
profit_level4_priority_feed_multiplier: 3.50
profit_level_other_priority_feed_multiplier: 4.00
use_multithreads_for_sending_swaps: False
list_errors_to_remove_pairs: "TRANSFER_FAILED;UniswapV2: K;INSUFFICIENT_INPUT_AMOUNT"
networks:
  default: mainnet-fork
  development:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
  kovan:
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
  from_key: ${PRIVATE_KEY}
coingecko_tokens_list_url: https://api.coingecko.com/api/v3/coins/list
dex:
  uniswap_v2:
    factory: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
    router: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    default_token: "WETH"
    use_graph: True
    is_master: True
    graph_url: "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2"
    graph_query: "query pairs {
      pairs(first: @size, orderBy: id, orderDirection: asc, where: {id_gt: \"@id\" reserve0_gt: 0, reserve1_gt: 0}) {
        id
        token0 {
          id
          symbol
          name
          decimals
        }
        token1 {
          id
          name
          symbol
          decimals
        }
      }
    }"
    graph_daily_Volume_query: "{
      pairDayDatas(
        first: @size
        skip: @skip
        orderBy: dailyVolumeUSD
        orderDirection: desc
        where: {date_gte: @time, dailyVolumeUSD_gt: 0}
      ) {
        dailyVolumeUSD
        pairAddress
      }
    }"   
  sushiswap:
    factory: "0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac"
    router: "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"
    default_token: "WETH"
    use_graph: True
    is_master: False
    graph_url: "https://api.thegraph.com/subgraphs/name/zippoxer/sushiswap-subgraph-fork"
    graph_query: "query pairs {
      pairs(first: @size, orderBy: id, orderDirection: asc, where: {id_gt: \"@id\" reserve0_gt: 0, reserve1_gt: 0}) {
        id
        token0 {
          id
          symbol
          name
          decimals
        }
        token1 {
          id
          name
          symbol
          decimals
        }
      }
    }"
    graph_daily_Volume_query: "{
      pairDayDatas(
        first: @size
        skip: @skip
        orderBy: dailyVolumeUSD
        orderDirection: desc
        where: {date_gte: @time, dailyVolumeUSD_gt: 0}
      ) {
        dailyVolumeUSD
        pairAddress
      }
    }"
